source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               icons/,\
               .,\
               lib/gson-2.13.2.jar,\
               lib/jakarta.inject-api-2.0.1.jar

